version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - '3333:3333'
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: blog_valentin
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: UkioZaVyDGnd7MMnrKmw
